<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Healthcare.Shared.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shared\Healthcare.Shared.Kernel\Healthcare.Shared.Kernel.csproj" />
    <ProjectReference Include="..\..\src\Shared\Healthcare.Shared.IntegrationBus\Healthcare.Shared.IntegrationBus.csproj" />
    <ProjectReference Include="..\..\src\Shared\Healthcare.Shared.Outbox\Healthcare.Shared.Outbox.csproj" />
  </ItemGroup>

</Project>
